#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
udocker_setup
=============

udocker installer with rich CLI

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import sys
import os
import argparse

__author__ = "udocker@lip.pt"
__copyright__ = "Copyright 2021, LIP"
__credits__ = ["udocker https://github.com/indigo-dc/udocker",
               "PRoot http://proot.me",
               "runC https://runc.io",
               "crun https://github.com/containers/crun",
               "Fakechroot https://github.com/dex4er/fakechroot",
               "Singularity http://singularity.lbl.gov"
              ]
__license__ = "Licensed under the Apache License, Version 2.0"
__version__ = "0.0.1"
__date__ = "2021"
STATUS_OK = 0
STATUS_ERROR = 1


class SetupCLI(object):
    """Implements the command line interface.
    These methods correspond directly to the commands that can
    be invoked via the command line interface.
    """

    # def __init__(self):
    #     self.localrepo

    def do_version(self, args):
        '''version: Show version'''
        print(__version__)
        return STATUS_OK

    def do_install(self, args):
        print('DOING Install')
        return STATUS_OK

    def do_show(self, args):
        print('DOING Show')
        return STATUS_OK

    def do_avail(self, args):
        pass

    def do_download(self, args):
        pass

    def do_download_all(self, args):
        pass

    def do_upgrade(self, args):
        pass

    def do_upgrade_all(self, args):
        pass

    def do_verify(self, args):
        pass

    def do_delete(self, args):
        pass

    def do_delete_all(self, args):
        pass

    def do_delete_metadata(self, args):
        pass


def main():
    """Program start and exception handling"""

    exit_status = STATUS_OK
    cli = SetupCLI()
    cmds_dict = {'version': cli.do_version, 'install': cli.do_install,
                 'show': cli.do_show, 'avail': cli.do_avail,
                 'download': cli.do_download, 
                 'download_all': cli.do_download_all,
                 'upgrade': cli.do_upgrade, 'upgrade_all': cli.do_upgrade_all,
                 'verify': cli.do_verify, 'delete': cli.do_delete,
                 'delete_all': cli.do_delete_all,
                 'delete_metadata': cli.do_delete_metadata}

    cmds = list(cmds_dict.keys())
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument('-v', '--verbose',
                       metavar='LEVEL',
                       help='verbosity level 0 (quiet) - 5 (debug)')
    group.add_argument('-q', '--quiet',
                       help='quiet (verbosity level 0)',
                       action='store_true')
    parser.add_argument('-c', '--conf',
                        help='use configuration file')
    parser.add_argument('cmd', help='Command',
                        choices=cmds)
    group.add_argument('--from',
                       metavar='url',
                       help='URL or local directory with modules')
    group.add_argument('--prefix',
                       metavar='dst_dir',
                       help='destination directory')
    parser.add_argument('-m', '--modules', metavar='modules', 
                        help='Modules', nargs='+')

    args = parser.parse_args()
    exit_status = cmds_dict[args.cmd](args)
    sys.exit(exit_status)

if __name__ == "__main__":
    main()
